language: node_js
node_js: "12"
cache: yarn

install:
  - yarn install
# TODO: figure out testing strategy.
# script:
#   - yarn test

deploy:
  - provider: script
    script: yarn deploy
    on:
      branch: master
