language: node_js
node_js: "12"
cache: yarn

before_install:
  - npm install -g yarn@2

install:
  - yarn install

# TODO: figure out testing strategy.
# script:
#   - yarn test

deploy:
  - provider: script
    script: yarn deploy
    on:
      branch: master
