language: node_js
node_js: "12"
cache: yarn

before_install:
  - npm install -g yarn@berry

install:
  - yarn install

script:
  - echo 'No tests yet!'
# TODO: figure out testing strategy.
#   - yarn test

deploy:
  - provider: script
    script: yarn deploy
    on:
      branch: master
